Added functions to configure mirrors with reflector and set mirror status

diff --git a/AFreshCupOfArch b/AFreshCupOfArch
--- a/AFreshCupOfArch
+++ b/AFreshCupOfArch
@@ -311,16 +311,53 @@ set_ntp() {
     fi
 }
 
+configure_mirrors() {
+    echo "Configuring mirrors..."
+
+    # Check to see if reflector is installed
+    if ! pacman -Qs reflector > /dev/null; then
+        echo "Installing reflector"
+        pacman -Sy --noconfirm reflector
+    fi
+
+    # Update mirrors
+    reflector --verbose --latest 5 --protocol https --sort score --threads 5 --save /etc/pacman.d/mirrorlist
+}
+
+check_mirrorlist_updated() {
+    echo "Checking if the mirrorlist has been updated by reflector..."
+    for i in {1..20}; do  # Check every 3 seconds for 60 seconds
+        if grep -q "Arch Linux mirrorlist generated by Reflector" /etc/pacman.d/mirrorlist; then
+            echo "Mirrorlist was updated by reflector."
+            return 0
+        fi
+        echo "waiting..."
+        sleep 3
+    done
+    echo "Mirrorlist was not updated within 60 seconds. Starting reflector service..."
+    systemctl start reflector.service
+    for i in {1..20}; do  # Additional 60 seconds to check
+        if grep -q "Arch Linux mirrorlist generated by Reflector" /etc/pacman.d/mirrorlist; then
+            echo "Mirrorlist was updated by reflector."
+            return 0
+        fi
+        echo "waiting..."
+        sleep 3
+    done
+    echo "Error: Reflector is not updating the mirrorlist."
+    return 1
+}
+
 
 main() {
     clear
     print_intro
     get_system_info
     set_required_vars
-    #configure_mirrors
-    #check_mirrorlist_updated
     check_connectivity
     set_ntp
+    configure_mirrors
+    check_mirrorlist_updated
     #show_mountpoints
     #get_install_disk
     #is_disk_encrypted_or_lvm
